version: '3'
services:
  cluster_manager:
    image: unum:latest
    networks:
      - control_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      PERIOD: "20s"
      LOG_LEVEL: "info"
      ORCHESTRATION: "localhost:2377"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  controller:
    image: cord/onos:latest
    networks:
      - control_net
    ports:
      - 8101:8101
    deploy:
      replicas: 3
      labels:
        org.onosproject.onos.cluster: "true"
    environment:
      JAVA_OPTS: "-Donos.cluster.metadata.uri=http://cluster_manager:5411/config/"

networks:
  control_net:
    driver: overlay

    # If you are using more than one network, you need label the network space to use for the
    # clustering
    labels:
      org.onosproject.onos.cluster: "true"
